name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get Qt 5 Patched
      run : |
        git -b kde/5.15 --depth=1 clone https://invent.kde.org/qt/qt/qt5.git --recursive
    - name: Configure
      run: |
        cd qt5
        ./configure -prefix ..\qt -opensource -nomake tests -confirm-license -nomake examples
    - name: Build
      run: |
        choco install jom
        cd qt5
        jom 
    - name: Pack
      shell: pwsh
      run: |
        Compress-Archive -Path .\qt\ qt.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: .\qt.zip
    - name: make distcheck
      run: make distcheck
