name: Windows

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get Qt 5 Patched
      run : |
        git clone -b kde/5.15 https://invent.kde.org/qt/qt/qt5.git --depth=1
        cd qt5
        git clone -b kde/5.15 https://invent.kde.org/qt/qt/qtbase.git --depth=1 --recursive
        git clone -b kde/5.15 https://invent.kde.org/qt/qt/qtsvg.git --depth=1 --recursive
        git clone -b kde/5.15 https://invent.kde.org/qt/qt/qtactiveqt.git --depth=1 --recursive
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure
      run: |
        cd qt5
        ./configure -prefix ..\qt -opensource -nomake tests -confirm-license -nomake examples -platform win32-msvc
    - name: Build
      run: |
        choco install jom
        cd qt5
        jom 
        jom install 
    - name: Pack
      shell: pwsh
      run: |
        Compress-Archive -Path .\qt\ qt.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: .\qt.zip
    - name: make distcheck
      run: make distcheck
