name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get Qt 5 Patched
      run : |
        git clone -b kde/5.15 https://invent.kde.org/qt/qt/qt5.git --recursive --depth=1 
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure
      run: |
        cd qt5
        ./configure -prefix ..\qt -opensource -nomake tests -confirm-license -nomake examples -platform win32-msvc -skip qtwebengine -skip qtandroidextras -skip qt3d -skip qtcanvas3d -skip qtcharts -skip qtconnectivity -skip qtdatavis3d  -skip qtgamepad -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtspeech -skip qtwebchannel -skip qtwebengine -skip qtwebsockets -skip qtwebview -skip qtvirtualkeyboard -skip qtdeclarative -
    - name: Build
      run: |
        choco install jom
        cd qt5
        jom 
    - name: Pack
      shell: pwsh
      run: |
        Compress-Archive -Path .\qt\ qt.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: .\qt.zip
    - name: make distcheck
      run: make distcheck
